name: Akamai as Code CI/CD Pipeline
on: [push]

jobs:
  Jobs:
    runs-on: gitea-runner
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EDGEGRID_ACCOUNT_KEY: ${{ secrets.EDGEGRID_ACCOUNT_KEY }}
      EDGEGRID_HOST: ${{ secrets.EDGEGRID_HOST }}
      EDGEGRID_ACCESS_TOKEN: ${{ secrets.EDGEGRID_ACCESS_TOKEN }}
      EDGEGRID_CLIENT_TOKEN: ${{ secrets.EDGEGRID_CLIENT_TOKEN }}
      EDGEGRID_CLIENT_SECRET: ${{ secrets.EDGEGRID_CLIENT_SECRET }}
      CONTRACT_ID: ${{ secrets.CONTRACT_ID }}
      GROUP_ID: ${{ secrets.GROUP_ID }}
      NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Prepare the environment
        run: chmod +x deploy.sh

      - name: Deploy
        run: ./deploy.sh
